# coding: utf-8
JEEDOM_COM = ''
log_level = "info"
apikey = ''
callback = ''
cycle = 0.3
cyclesommeil = 0.5
inverter_name = ''
lookup_file = ''
ideqpmnt = 0
inverter_host = ''
inverter_port = 8899
inverter_sn = 0
inverter_mb_slaveid = 1
path = '../data/inverters/'
